export const TEXTS = {
  APP_NAME: "FACTn Assistant", 
  APP_TAGLINE: "Skip the AI Ops. Just Build the Experience.",
  COMAPNY_NAME: "FACTn Software"
}


export const GEMINI_VOICES = [
  { name: "Zephyr",          tone: "Bright" },
  { name: "Puck",            tone: "Upbeat" },
  { name: "Charon",          tone: "Informative" },
  { name: "Kore",            tone: "Firm" },
  { name: "Fenrir",          tone: "Excitable" },
  { name: "Leda",            tone: "Youthful" },
  { name: "Orus",            tone: "Firm" },
  { name: "Aoede",           tone: "Breezy" },
  { name: "Callirrhoe",      tone: "Easy-going" },
  { name: "Autonoe",         tone: "Bright" },
  { name: "Enceladus",       tone: "Breathy" },
  { name: "Iapetus",         tone: "Clear" },
  { name: "Umbriel",         tone: "Easy-going" },
  { name: "Algieba",         tone: "Smooth" },
  { name: "Despina",         tone: "Smooth" },
  { name: "Erinome",         tone: "Clear" },
  { name: "Algenib",         tone: "Gravelly" },
  { name: "Rasalgethi",      tone: "Informative" },
  { name: "Laomedeia",       tone: "Upbeat" },
  { name: "Achernar",        tone: "Soft" },
  { name: "Alnilam",         tone: "Firm" },
  { name: "Schedar",         tone: "Even" },
  { name: "Gacrux",          tone: "Mature" },
  { name: "Pulcherrima",     tone: "Forward" },
  { name: "Achird",          tone: "Friendly" },
  { name: "Zubenelgenubi",   tone: "Casual" },
  { name: "Vindemiatrix",    tone: "Gentle" },
  { name: "Sadachbia",       tone: "Lively" },
  { name: "Sadaltager",      tone: "Knowledgeable" },
  { name: "Sulafat",         tone: "Warm" },
];


// Tone → subtle badge colour mapping
export const TONE_COLORS: Record<string, string> = {
  Bright:        "bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-300",
  Upbeat:        "bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300",
  Informative:   "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
  Firm:          "bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300",
  Excitable:     "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
  Youthful:      "bg-pink-100 text-pink-800 dark:bg-pink-900/30 dark:text-pink-300",
  Breezy:        "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300",
  "Easy-going":  "bg-teal-100 text-teal-800 dark:bg-teal-900/30 dark:text-teal-300",
  Breathy:       "bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300",
  Clear:         "bg-sky-100 text-sky-800 dark:bg-sky-900/30 dark:text-sky-300",
  Smooth:        "bg-indigo-100 text-indigo-800 dark:bg-indigo-900/30 dark:text-indigo-300",
  Gravelly:      "bg-stone-100 text-stone-800 dark:bg-stone-800 dark:text-stone-300",
  Soft:          "bg-rose-100 text-rose-800 dark:bg-rose-900/30 dark:text-rose-300",
  Even:          "bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-300",
  Mature:        "bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300",
  Forward:       "bg-lime-100 text-lime-800 dark:bg-lime-900/30 dark:text-lime-300",
  Friendly:      "bg-emerald-100 text-emerald-800 dark:bg-emerald-900/30 dark:text-emerald-300",
  Casual:        "bg-violet-100 text-violet-800 dark:bg-violet-900/30 dark:text-violet-300",
  Gentle:        "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900/30 dark:text-fuchsia-300",
  Lively:        "bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-300",
  Knowledgeable: "bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300",
  Warm:          "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300",
}


export const SUPPORTED_LANGUAGES = [
  { code: "ar",  name: "Arabic" },
  { code: "bn",  name: "Bangla" },
  { code: "nl",  name: "Dutch" },
  { code: "en",  name: "English" },
  { code: "fr",  name: "French" },
  { code: "de",  name: "German" },
  { code: "hi",  name: "Hindi" },
  { code: "id",  name: "Indonesian" },
  { code: "it",  name: "Italian" },
  { code: "ja",  name: "Japanese" },
  { code: "ko",  name: "Korean" },
  { code: "mr",  name: "Marathi" },
  { code: "pl",  name: "Polish" },
  { code: "pt",  name: "Portuguese" },
  { code: "ro",  name: "Romanian" },
  { code: "ru",  name: "Russian" },
  { code: "es",  name: "Spanish" },
  { code: "ta",  name: "Tamil" },
  { code: "te",  name: "Telugu" },
  { code: "th",  name: "Thai" },
  { code: "tr",  name: "Turkish" },
  { code: "uk",  name: "Ukrainian" },
  { code: "vi",  name: "Vietnamese" },
  { code: "af",  name: "Afrikaans" },
  { code: "sq",  name: "Albanian" },
  { code: "am",  name: "Amharic" },
  { code: "hy",  name: "Armenian" },
  { code: "az",  name: "Azerbaijani" },
  { code: "eu",  name: "Basque" },
  { code: "be",  name: "Belarusian" },
  { code: "bg",  name: "Bulgarian" },
  { code: "my",  name: "Burmese" },
  { code: "ca",  name: "Catalan" },
  { code: "ceb", name: "Cebuano" },
  { code: "cmn", name: "Chinese, Mandarin" },
  { code: "hr",  name: "Croatian" },
  { code: "cs",  name: "Czech" },
  { code: "da",  name: "Danish" },
  { code: "et",  name: "Estonian" },
  { code: "fil", name: "Filipino" },
  { code: "fi",  name: "Finnish" },
  { code: "gl",  name: "Galician" },
  { code: "ka",  name: "Georgian" },
  { code: "el",  name: "Greek" },
  { code: "gu",  name: "Gujarati" },
  { code: "ht",  name: "Haitian Creole" },
  { code: "he",  name: "Hebrew" },
  { code: "hu",  name: "Hungarian" },
  { code: "is",  name: "Icelandic" },
  { code: "jv",  name: "Javanese" },
  { code: "kn",  name: "Kannada" },
  { code: "kok", name: "Konkani" },
  { code: "lo",  name: "Lao" },
  { code: "la",  name: "Latin" },
  { code: "lv",  name: "Latvian" },
  { code: "lt",  name: "Lithuanian" },
  { code: "lb",  name: "Luxembourgish" },
  { code: "mk",  name: "Macedonian" },
  { code: "mai", name: "Maithili" },
  { code: "mg",  name: "Malagasy" },
  { code: "ms",  name: "Malay" },
  { code: "ml",  name: "Malayalam" },
  { code: "mn",  name: "Mongolian" },
  { code: "ne",  name: "Nepali" },
  { code: "nb",  name: "Norwegian, Bokmål" },
  { code: "nn",  name: "Norwegian, Nynorsk" },
  { code: "or",  name: "Odia" },
  { code: "ps",  name: "Pashto" },
  { code: "fa",  name: "Persian" },
  { code: "pa",  name: "Punjabi" },
  { code: "sr",  name: "Serbian" },
  { code: "sd",  name: "Sindhi" },
  { code: "si",  name: "Sinhala" },
  { code: "sk",  name: "Slovak" },
  { code: "sl",  name: "Slovenian" },
  { code: "sw",  name: "Swahili" },
  { code: "sv",  name: "Swedish" },
  { code: "ur",  name: "Urdu" },
]