import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import HomeHeader from "@/components/user/home-header";
import { ThemeToggler } from "@/components/theme-toggler";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="brand-shell min-h-screen">
      <HomeHeader />
      <ThemeToggler className="fixed bottom-4 left-1/2 z-50 -translate-x-1/2 sm:left-6 sm:translate-x-0" />
      <main className="relative pt-24 sm:pt-28">{children}</main>
    </div>
  );
}